### ISSUE TITLE
Compile Issue with 3rdparty Library under Linux (X11)

### ISSUE THREAD

**Issue by jrw77** [607011/clip2data2clip#2]
The file clip_x11.cpp ist corrupted and does not compile. This file is probably only used under Linux with X11.
A corrected file that compiles  (`format` -> `format f` in line 244 and 1098) does not seem to work as expected.

original compile error: 

`./clip2png2clip/3rdparty/clip/clip_x11.cpp: In member function ‘bool clip::{anonymous}::Manager::get_mime_type(clip::format, std::__cxx11::string&) const’:
./clip2png2clip/3rdparty/clip/clip_x11.cpp:245:25: error: ‘f’ was not declared in this scope
     if (!is_convertible(f))
                         ^
`

**Comment by 607011** [comment]
A [commit](https://github.com/607011/clip/commit/5c617daa125740375fdbc86491b16e76f7e13115) as of March 15th fixed the bug. But … when you `git submodule update`, not the `main` branch is checked out but some commit which is detached from `HEAD`. Please use `git submodule update --remote --merge` to update the local submodule.

**Comment by 607011** [comment]
Fixed (see 8dfba39ea84a0bf3b834a5a325ec6945f4c03eeb)
